# Generated by Django 3.0 on 2024-01-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_auto_20240122_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
    ]
